version: "3.8"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  db:
    image: mysql:5.7.13
    # container_name: mysql_Python
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "buildings"

  backend:
      build: 
          context: .
          dockerfile: Dockerfile
      volumes: 
          - ./app:/app
      ports: 
          - 5000:5000
      build: ./app
      depends_on: 
          - db
      links: 
          - db:db

volumes:
  db_data: {}
